# ===============================
#   twilio configurations
# ===============================
twilio:
  account_sid: AC6c2ead20ebd298333c3df7831633b071
  auth_token: e3ee6e2ce667c0a18ab9034c90373322
  trial_number: +13342924705
  
  
# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbprojet430
    username: projet430
    password: groupe7

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = MAIL configurations
# ===============================
  mail:
    default-encoding: UTF-8
    #host: smtp.gmail.com
    #username: username@gmail.com
    #password: secret
    #port: 587
    host: smtp.gmail.com
    username: agpe.uy1@gmail.com
    password: agpe_groupe7
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
  
  
  